myprog: 03functions.o 03bfunctiondefs.o
	g++ 03functions.o 03bfunctiondefs.o -o myprog

03functions.o: 03functions.cc
	g++ -c 03functions.cc

03bfunctiondefs.o: 03bfunctiondefs.cc
	g++ -c 03bfunctiondefs.cc
