code --install-extension eamodio.gitlens &&^
code --install-extension ms-vscode.cpptools &&^
code --install-extension vscjava.vscode-java-pack &&^
code --install-extension ms-vsliveshare.vsliveshare-pack &&^
code --install-extension esbenp.prettier-vscode &&^
code --install-extension ms-python.python &&^
code --install-extension aaron-bond.better-comments &&^
code --install-extension Gruntfuggly.todo-tree &&^
code --install-extension ms-vscode-remote.vscode-remote-extensionpack &&^
code --install-extension dan-c-underwood.arm &&^
code --install-extension adashen.vscode-tomcat &&^
code --install-extension yzhang.markdown-all-in-one &&^
echo "DONE INSTALLING EXTENSIONS"
